sudo: required
language: generic

services:
  - docker

before_install:
   - docker build -t asad-mallick/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true asad-mallick/client-test npm test

after_success:
  - docker build -t mallickasad/multi-client ./client
  - docker build -t mallickasad/multi-nginx ./nginx
  - docker build -t mallickasad/multi-server ./server
  - docker build -t mallickasad/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mallickasad/multi-client
  - docker push mallickasad/multi-nginx
  - docker push mallickasad/multi-server
  - docker push mallickasad/multi-worker

    # deploying to aws beanstalk

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-1-710765160302
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

