sudo: required
services:
  - docker

before_install:
   - docker build -t asad-mallick/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true asad-mallick/client-test npm test

after_success:
  - docker build -t asad-mallick/multi-client ./client
  - docker build -t asad-mallick/multi-nginx ./nginx
  - docker build -t asad-mallick/multi-server ./server
  - docker build -t asad-mallick/multi-worker ./worker
  # login to docker CLI
  - echo "$Docker_password" | docker login -u "$Docker_id" --password-stdin
  # Take those images and push them to docker hub
  - docker push asad-mallick/multi-client
  - docker push asad-mallick/multi-nginx
  - docker push asad-mallick/multi-server
  - docker push asad-mallick/multi-worker
